### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "17fce83883b3440d9d45963324c26159",
  "accountNumber": "1000000001",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/17fce83883b3440d9d45963324c26159
